# Generated by Django 6.0 on 2025-12-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_stockhistory_date_alter_contacts_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
    ]
