# Generated by Django 6.0 on 2025-12-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_supplier_stock_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
